### ISSUE TITLE
LivingSetAttackTargetEvent; Puts server in infinite loop.

### ISSUE THREAD

**Issue by darkshadow1809** [Corosauce/ZombieAwareness#11]
https://paste.ubuntu.com/23642192/

On line 21507 The error starts.

It seems it will spam the console 

`        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) ~[lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) ~[lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) ~[lr.class:?]
        at farseek.world.chunk.package$.provideChunk(package.scala:11) ~[package$.class:?]
        at farseek.world.chunk.package.provideChunk(package.scala) ~[package.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
        at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
        at net.minecraft.world.World.func_180495_p(World.java:842) ~[aid.class:?]
        at net.minecraft.world.World.func_147447_a(World.java:878) ~[aid.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70685_l(EntityLivingBase.java:2340) ~[sf.class:?]
        at ZombieAwareness.ZAUtil.tryPlayTargetSound(ZAUtil.java:994) ~[ZAUtil.class:?]
        at ZombieAwareness.ZAUtil.hookSetAttackTarget(ZAUtil.java:653) ~[ZAUtil.class:?]
        at ZombieAwareness.ZAEventHandler.setAttackTarget(ZAEventHandler.java:40) ~[ZAEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1012_ZAEventHandler_setAttackTarget_LivingSetAttackTargetEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:488) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70604_c(EntityLivingBase.java:437) ~[sf.class:?]
        at net.minecraft.entity.monster.EntityPigZombie.func_70604_c(SourceFile:47) ~[yy.class:?]
        at net.minecraft.entity.monster.EntityPigZombie.func_70037_a(SourceFile:137) ~[yy.class:?]
        at net.minecraft.entity.Entity.func_70020_e(Entity.java:1704) ~[rw.class:?]
        at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:175) ~[ry.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:597) ~[atj.class:?]
[12:14:20] [Server thread/ERROR] [FML]: Index: 5 Listeners:
[12:14:20] [Server thread/ERROR] [FML]: 0: NORMAL
[12:14:20] [Server thread/ERROR] [FML]: 1: ASM: funwayguy.epicsiegemod.handlers.MainHandler@1abd3303 onTargetSet(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V
[12:14:20] [Server thread/ERROR] [FML]: 2: ASM: elucent.roots.EventManager@47030049 onTargetEvent(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V
[12:14:20] [Server thread/ERROR] [FML]: 3: ASM: elucent.roots.EventManager@47030049 onLivingTarget(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V
[12:14:20] [Server thread/ERROR] [FML]: 4: ASM: xreliquary.handler.CommonEventHandler@66198502 onEntityTargetedEvent(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V
[12:14:20] [Server thread/ERROR] [FML]: 5: ASM: ZombieAwareness.ZAEventHandler@608cbe49 setAttackTarget(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V`

Also it seems to like to spam this a lot.

`f84e
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 46062528-acc7-43de-9ff2-03c58ac58e20
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 0dddb62a-f637-40c4-9399-bc63bb43f84e
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 46062528-acc7-43de-9ff2-03c58ac58e20
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 0dddb62a-f637-40c4-9399-bc63bb43f84e
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 0dddb62a-f637-40c4-9399-bc63bb43f84e
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 46062528-acc7-43de-9ff2-03c58ac58e20
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 0dddb62a-f637-40c4-9399-bc63bb43f84e
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 0dddb62a-f637-40c4-9399-bc63bb43f84e
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 46062528-acc7-43de-9ff2-03c58ac58e20
[12:17:49] [Server thread/WARN]: Keeping entity PigZombie that already exists with UUID 46062528-acc7-43de-9ff2-03c58ac58e20`

Using latest version of zombie awareness on curse for 1.10.2

The server continues doing this in an endless loop. Left it running for 2 hours. Cycling back and forth between those two messages. Seems it only happens in the nether and it involves the pigman as you can see,

**Comment by Corosauce** [comment]
Hoping https://github.com/Corosauce/ZombieAwareness/commit/77be1779ebe837185d1549c8f15aa7c2b4eec1db will fix it, might be an edge case, not the first chunkloading issue the new feature has introduced.

What dimension was the player in during this? I assume the pigzombies were in the nether, were you as well? Trying to make sense of exactly why this issue was happening.

**Comment by Corosauce** [comment]
No more reports about this, considering it fixed.
