### ISSUE TITLE
Random Crash dont know if its this mod or your weather mod [server side]

### ISSUE THREAD

**Issue by VirtualGaming1** [Corosauce/ZombieAwareness#36]
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at net.minecraft.nbt.NBTTagCompound.func_152448_b(NBTTagCompound.java:486)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:56)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:83)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:89)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:69)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:309)
	at net.minecraft.world.World.func_175726_f(World.java:304)
	at net.minecraft.world.World.func_180495_p(World.java:910)
	at weather2.weathersystem.storm.TornadoHelper.tick(TornadoHelper.java:320)
	at weather2.weathersystem.storm.StormObject.tick(StormObject.java:570)
	at weather2.weathersystem.WeatherManagerBase.tick(WeatherManagerBase.java:138)
	at weather2.weathersystem.WeatherManagerServer.tick(WeatherManagerServer.java:52)
	at weather2.ServerTickHandler.onTickInGame(ServerTickHandler.java:92)
	at weather2.EventHandlerFML.tickServer(EventHandlerFML.java:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_577_EventHandlerFML_tickServer_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

https://github.com/Corosauce/weather2/issues/285

**Comment by VirtualGaming1** [comment]
using Forge-1.12.2-14.23.4.2705 Minecraft Forge Rec

**Comment by VirtualGaming1** [comment]
diffrent mod
