### ISSUE TITLE
Crashes in server instance [1.18.1]

### ISSUE THREAD

**Issue by itsdinkd** [Corosauce/ZombieAwareness#57]
```java
[18:43:18] [main/WARN]: @Redirect conflict. Skipping zombieawareness.mixins.json:MixinLevelEvent->@Redirect::broadcast(Lnet/minecraft/server/players/PlayerList;Lnet/minecraft/world/entity/player/Player;DDDDLnet/minecraft/resources/ResourceKey;Lnet/minecraft/network/protocol/Packet;)V with priority 1000, already redirected by vanishmod.mixins.json:world.MixinServerLevel->@Redirect::redirectBroadcast(Lnet/minecraft/server/players/PlayerList;Lnet/minecraft/world/entity/player/Player;DDDDLnet/minecraft/resources/ResourceKey;Lnet/minecraft/network/protocol/Packet;)V with priority 1000
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.9/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:40)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16)
        at MC-BOOTSTRAP/datafixerupper@4.0.26/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:28)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:18)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.data.BuiltinRegistries.m_194668_(BuiltinRegistries.java:38)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.data.BuiltinRegistries.m_194659_(BuiltinRegistries.java:93)
        at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:92)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.core.Registry.<clinit>(Registry.java:517)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:45)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.Main.main(Main.java:101)
        ... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector broadcast(Lnet/minecraft/server/players/PlayerList;Lnet/minecraft/world/entity/player/Player;DDDDLnet/minecraft/resources/ResourceKey;Lnet/minecraft/network/protocol/Packet;)V in zombieawareness.mixins.json:MixinLevelEvent failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap zombieawareness.refmap.json
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 40 more
        ```
        
        Cannot start server

**Comment by blood789** [comment]
Hello, have you find the reason and solution?

**Comment by itsdinkd** [comment]
yes. it was conflicting with a mod called Vanish Mod. I removed the mod.

**Comment by blood789** [comment]
It was strange, i have no use the a mod called Vanish Mod.....
