### ISSUE TITLE
[1.18.1] Ticking Entity v1.12.3 crash server

### ISSUE THREAD

**Issue by itsdinkd** [Corosauce/ZombieAwareness#63]
```java
[16:41:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.corosus.zombieawareness.client.SoundProfileEntry.getSoundName()" because "entry" is null
        at com.corosus.zombieawareness.ZAUtil.getSoundIDEntry(ZAUtil.java:150) ~[zombieawareness-1.18.1-1.12.3.jar%23316!:1.18.1-1.12.3]
        at com.corosus.zombieawareness.ZAUtil.hookSoundEvent(ZAUtil.java:529) ~[zombieawareness-1.18.1-1.12.3.jar%23316!:1.18.1-1.12.3]
        at net.minecraft.server.level.ServerLevel.handler$bdd000$injectBroadcast(ServerLevel.java:4100) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.level.ServerLevel.m_6263_(ServerLevel.java:883) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.world.entity.Entity.m_5496_(Entity.java:958) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.world.entity.monster.Slime.m_8119_(Slime.java:137) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:649) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23318!:?]
        ... 5 more
        ```

Full crash log https://pastebin.com/cTPssrBA

**Comment by itsdinkd** [comment]
It's concerning that sound is trying to play on a server..
